### ISSUE TITLE
질문있습니다. venv 대신 pipenv 를 사용해도 괜찮을까요?

### ISSUE THREAD

**Issue by joyoon729** [edutak/myb#1]
안녕하세요. 😃 

본 수업에서는 `venv` 를 사용해 가상환경을 만들어 진행하셨는데요,

찾아보니 파이썬에서 공식적으로 권장하는 `pipenv` 라는 툴이 있더라구요.

1. 오늘 수업에 `pipenv` 대신 `venv` 를 사용하신 이유가 있는지 알고싶고,
2. 수업 내용에 `pipenv` 를 사용해도 되는지 알고 싶습니다.

선생님께서 수업 중에 `anaconda` 는 이 프로젝트에 사용이 안된다고 하신것 같아서요.

3. 또 `pipenv` 는 `requirements.txt` 대신에 `Pipfile.lock` 을 사용한다는데 헤로쿠로 배포하는데 지장이 없을지 알고싶습니다.

**Comment by edutak** [comment]
1, 2. 파이썬에서 *공식으로 권장하는* 이라는 말을 어떻게 받아드려야할지 모르겠지만, 다른 패키지 설치 없이 사용할 수 있는 패키지가 오히려 `venv` 입니다!  [파이썬 문서 링크](https://docs.python.org/3/library/venv.html)
또한, 수업에서 진행되기 위해서는 조금 더 편리하게 사용할 수 있는 툴을 (학습곡선이 낮음) 선택을 해야하는데, 파이썬 내장이면서 사용에 문제 없는 `venv`를 하였습니다. 명령어 한줄로 만들어지고 관리할 수 있기 때문이죠! 편의성/장단점으로 인해 다른 라이브러리를 사용하는 것은 얼마든지 가능합니다 :) 가상환경과 관련된 패키지/라이브러리들은 워낙 많이 있고, 그 중에 개인적 선호도를 통해 선택을 하면 되기 때문이죠. 환경변수 역시도 마찬가지입니다.

그리고 `anaconda` 를 굳이 사용할 이유가 없다는 의미였습니다. 헤로쿠 배포시 설치가 안되는 패키지가 포함되어 있습니다. 

3. 지장 없습니다.
